name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Install twine
      run: python -m pip install twine

    - name: Install setuptools_scm
      run: python -m pip install setuptools_scm
    
    - name: Build package
      run: python -m build --sdist --wheel

    - name: Publish package
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "[distutils]" > ~/.pypirc
        echo "index-servers =" >> ~/.pypirc
        echo "    pypi" >> ~/.pypirc
        echo "[pypi]" >> ~/.pypirc
        echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
        echo "username: __token__" >> ~/.pypirc
        echo "password: $PYPI_API_TOKEN" >> ~/.pypirc

        VERSION=$(python -c "from setuptools_scm import get_version; print(get_version())")
        if twine check --config-file ~/.pypirc dist/* 2>&1 | grep -q "File already exists"; then
          echo "Package version already exists on PyPI. Increasing version number..."
          NEW_VERSION=$(python -c "from packaging.version import Version; v = Version('$VERSION'); v = v.bump_patch(); print(v)")
          echo "New version: $NEW_VERSION"
          sed -i "s/version=\"$VERSION\"/version=\"$NEW_VERSION\"/g" setup.py
          python -m build --sdist --wheel
        fi

        twine upload --config-file ~/.pypirc dist/*
