name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm build twine

    - name: Install twine
      run: python -m pip install twine

    - name: Install setuptools_scm
      run: python -m pip install setuptools_scm
    
    - name: Build package
      run: python -m build

    - name: Update version
      run: |
        CURRENT_VERSION=$(python -c "import setuptools_scm.version; print(setuptools_scm.version.tag_to_version()")
        NEW_VERSION="$CURRENT_VERSION"
        while twine check --config-file ~/.pypirc dist/* | grep -q "File already exists"; do
          NEW_VERSION=$(python -c "parts = '$NEW_VERSION'.split('.'); parts[-1] = str(int(parts[-1]) + 1); print('.'.join(parts))")
          echo "Updating version to $NEW_VERSION"
          sed -i "s/version=\"$CURRENT_VERSION\"/version=\"$NEW_VERSION\"/" setup.py
        done

    - name: Publish package
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "[distutils]" > ~/.pypirc
        echo "index-servers =" >> ~/.pypirc
        echo "    pypi" >> ~/.pypirc
        echo "[pypi]" >> ~/.pypirc
        echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
        echo "username: __token__" >> ~/.pypirc
        echo "password: $PYPI_API_TOKEN" >> ~/.pypirc
        twine upload --config-file ~/.pypirc dist/* --verbose
